name: ts_hid
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  universal_html: ^2.2.4
  intl: ^0.19.0
  http: ^1.2.2
  syncfusion_flutter_charts: ^26.2.14
  lottie: ^3.1.2
  awesome_snackbar_content: ^0.1.4
  shared_preferences: ^2.2.3
  local_auth: ^2.3.0
  flutter_email_sender: ^6.0.3
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: NokiaPureText
      fonts:
        - asset: assets/NokiaPureText_Rg.ttf
          weight: 500
        - asset: assets/NokiaPureText_Lt.ttf
          weight: 200
        - asset: assets/NokiaPureText_Md.ttf
          weight: 400
    - family: NokiaPureHeadline
      fonts:
        - asset: assets/NokiaPureHeadline_ULt.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  remove_alpha_ios: true
